namespace ACMESharp.Messages
{
    /// <summary>
    /// Defines a server response message that conforms to the "Problem Details"
    /// JSON structure as specified in
    /// <see cref="http://tools.ietf.org/html/draft-ietf-appsawg-http-problem-02"
    /// >[I-D.ietf-appsawg-http-problem]</see>.
    /// This structure is used by ACME to provide further details of a reported
    /// error as described in the
    /// <see cref="https://ietf-wg-acme.github.io/acme/#rfc.section.5.4"
    /// >ACME spec 5.4</see>.
    /// </summary>
    public class ProblemDetailResponse
    {
        public const string CONTENT_TYPE = "application/problem+json";

        /// <summary>
        /// An absolute URI [RFC3986] that identifies the
        /// problem type.  When dereferenced, it SHOULD provide human-readable
        /// documentation for the problem type (e.g., using HTML
        /// [W3C.REC-html401-19991224]).  When this member is not present, its
        /// value is assumed to be "about:blank".
        /// </summary>
        public string Type
        { get; set; }

        /// <summary>
        /// A short, human-readable summary of the problem
        /// type.  It SHOULD NOT change from occurrence to occurrence of the
        /// problem, except for purposes of localisation.
        /// </summary>
        public string Title
        { get; set; }

        /// <summary>
        /// The HTTP status code ([RFC7231], Section 6)
        /// generated by the origin server for this occurrence of the problem.
        /// </summary>
        public int Status
        { get; set; }

        /// <summary>
        /// An human readable explanation specific to this
        /// occurrence of the problem.
        /// </summary>
        public string Detail
        { get; set; }

        /// <summary>
        /// An absolute URI that identifies the specific
        /// occurrence of the problem.  It may or may not yield further
        /// information if dereferenced.
        /// </summary>
        public string Instance
        { get; set; }

        /// <summary>
        /// Supplies the original, unparsed, unprocessed content that was
        /// used to populate this Response object.
        /// </summary>
        public string OrignalContent
        { get; set; }
    }
}
